### ISSUE TITLE
upload_file中的make_reporthook似乎无法使用？

### ISSUE THREAD

**Issue by TyroneVeblen** [ChenyangGao/p115client#2]
按照文档，我是这样使用client.upload_file的
![image](https://github.com/user-attachments/assets/98da711b-7330-48b3-8294-8a12cb0b8c37)
但这样似乎无效。
随后看了下源代码（但是看不懂），
使用upload_directly=True下（不使用这个参数会报错“请重新登录”）
client.upload_file会返回yield self.upload_file_sample
而这个self.upload_file_sample会在gen_step()开头检查make_reporthook是不是一个callable
是的话就把dataiter赋值为progress_bytes_iter或者progress_bytes_async_iter

但是这个dataiter似乎没有被使用？
我尝试在progress_bytes_iter的最开始添加了一段print语句，但是print语句并没有被执行，如果增加一段dataiter.__next__()则可以看到tqdm正确显示了总大小，print语句也有执行

也许意味着我需要手动更新进度条？

但是看https://p115client.readthedocs.io/en/latest/reference/client.html#p115client.client.P115Client.upload_file

和progress_bytes_iter的源代码，似乎正确的运作方式是传入一个带有update()的callable就会自动update。但实际上并不奏效。。。

那么究竟应该怎么做呢？有没有示例给一个？

**Comment by ChenyangGao** [comment]
upload_directly是有bug，已修复，升级模块

**Comment by TyroneVeblen** [comment]
> upload_directly是有bug，已修复，升级模块

可以用了，谢谢大佬
